batch_size: 512
ce_weight: 1.0
checkpoint_metric: perplexity
cuda: true
device: cuda
embedding_dim: 10
experiment_name: E007_CompositionalXKCDModel
hparams_load_path: ../configs/E007_CompositionalXKCDModel.yaml
input_size: 54
learning_rate: 0.01
lstm_size: 32
max_seq_len: 6
num_epochs: 200
num_lstm_layers: 2
patience_threshold: 4
root_output_path: /common/users/ssd122/speaker_strategies_storage/compositional_model/logs
seed: 1337
teacher_phi_path: /common/users/ssd122/speaker_strategies_storage/compositional_model/logs/E006_calibrations/99th_percentile/calibrated_phis_99percentile.npy
teacher_phi_weight: 50.0
trial_name: trial1_teacher_phi_weight_50
use_ce: true
use_teacher_phi: true
vocab_size: 340
weight_decay: 0.0
xkcd_coordinate_system: fft
