batch_size: 256
checkpoint_metric: perplexity
cuda: false
device: cpu
embedding_dim: 10
experiment_name: E005_CompositionalModel
hparams_load_path: ../configs/E005_CompositionalModel.yaml
input_size: 3
learning_rate: 0.01
lstm_size: 32
max_seq_len: 6
num_epochs: 200
num_lstm_layers: 2
patience_threshold: 4
root_output_path: /common/users/ssd122/speaker_strategies_storage/compositional_model/logs
seed: 1337
trial_name: trial2
vocab_size: 340
weight_decay: 0.0
xkcd_coordinate_system: fft
