# Experiment Hyper Params
experiment_name: E005_CompositionalModel
trial_name: trial1-probs
root_output_path: "/common/users/ssd122/speaker_strategies_storage/compositional_model/logs"
xkcd_coordinate_system: fft

# Training Hyper Params
seed: 1337
num_epochs: 200
batch_size: 256
checkpoint_metric: perplexity
learning_rate: 0.01
patience_threshold: 4
# overall l2
weight_decay: 0.000

# Model Hyper Params
input_size: -1
lstm_size: 32
num_lstm_layers: 2
embedding_dim: 10
vocab_size: -1
max_seq_len: 6

# Runtime params
cuda: true